all: command1 command2

command1:
	gcc -L/home/uig70502/Documents/Probleme/My_library -Wl,-rpath=/home/uig70502/Documents/Probleme/My_library -Wall -o buildtime-link main.c -lsample

command2:
	./buildtime-link